module TinyAdmin
  module Plugins
    class BaseRepository
      class RecordNotFound < StandardError
      end

      attr_reader model: untyped

      def initialize: (untyped) -> void

      def page_offset: (Integer, Integer) -> Integer
    end
  end
end
