module TinyAdmin
  module Plugins
    class SequelRepository < BaseRepository
      def apply_filters: (untyped, Enumerable[untyped]) -> untyped

      def collection: () -> untyped

      def fields: (?options: Hash[untyped, untyped]?) -> Hash[String, Field]

      def find: (untyped) -> untyped

      def index_record_attrs: (untyped, ?fields: Hash[untyped, untyped]?) -> Hash[untyped, untyped]

      def index_title: () -> String

      def list: (?page: Integer, ?limit: Integer, ?sort: untyped?, ?filters: untyped?) -> [Array[untyped], Integer]

      def show_title: (untyped) -> String

      alias show_record_attrs index_record_attrs

      private

      def sequel_type_to_sym: (untyped) -> Symbol

      def apply_hash_filter: (untyped, Field, Hash[untyped, untyped]) -> untyped

      def apply_scalar_filter: (untyped, Field, untyped) -> untyped
    end
  end
end
