# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rack'
gem 'webrick'

gem 'hanami-router'

gem 'tiny_admin', path: '../../'
