module TinyAdmin
  class Settings
    DEFAULTS: Hash[Array[Symbol], untyped]
    OPTIONS: Array[Symbol]
    VALID_SECTION_TYPES: Array[Symbol]
    REPOSITORY_INTERFACE: Array[Symbol]

    @options: Hash[Array[Symbol], untyped]

    attr_reader store: Store

    # Dynamically defined accessors for OPTIONS
    def authentication: () -> untyped
    def authentication=: (untyped) -> untyped
    def authorization_class: () -> untyped
    def authorization_class=: (untyped) -> untyped
    def components: () -> untyped
    def components=: (untyped) -> untyped
    def content_page: () -> untyped
    def content_page=: (untyped) -> untyped
    def extra_styles: () -> untyped
    def extra_styles=: (untyped) -> untyped
    def helper_class: () -> untyped
    def helper_class=: (untyped) -> untyped
    def page_not_allowed: () -> untyped
    def page_not_allowed=: (untyped) -> untyped
    def page_not_found: () -> untyped
    def page_not_found=: (untyped) -> untyped
    def record_not_found: () -> untyped
    def record_not_found=: (untyped) -> untyped
    def repository: () -> untyped
    def repository=: (untyped) -> untyped
    def root: () -> untyped
    def root=: (untyped) -> untyped
    def root_path: () -> untyped
    def root_path=: (untyped) -> untyped
    def sections: () -> untyped
    def sections=: (untyped) -> untyped
    def scripts: () -> untyped
    def scripts=: (untyped) -> untyped
    def strict_config: () -> untyped
    def strict_config=: (untyped) -> untyped
    def style_links: () -> untyped
    def style_links=: (untyped) -> untyped

    def []: (*String | Symbol) -> untyped

    def []=: (*String | Symbol, untyped) -> untyped

    def load_settings: () -> void

    def reset!: () -> void

    private

    def convert_value: (untyped, untyped) -> void

    def fetch_setting: (Array[String | Symbol]) -> Array[untyped]

    def validate_config!: () -> void

    def config_problem: (String) -> void
  end
end
