module TinyAdmin
  module Actions
    class CsvExport < BasicAction
      def call: (app: BasicApp, context: Context, options: Hash[Symbol, untyped]) -> untyped

      private

      def prepare_filters: (Hash[String, Field], Hash[String, untyped], Hash[Symbol, untyped]) -> Hash[Field, Hash[Symbol, untyped]]

      def build_csv: (Array[untyped], Hash[String, Field], untyped, untyped) -> String
    end
  end
end
