module TinyAdmin
  module Actions
    class Index < BasicAction
      attr_reader context: untyped
      attr_reader current_page: Integer
      attr_reader fields_options: untyped
      attr_reader links: untyped
      attr_reader options: untyped
      attr_reader pagination: Integer
      attr_reader pages: untyped
      attr_reader params: untyped
      attr_reader query_string: String
      attr_reader repository: untyped
      attr_reader sort_params: untyped

      def call: (app: BasicApp, context: Context, options: Hash[Symbol, untyped]) -> untyped

      private

      def evaluate_options: (Hash[Symbol, untyped]) -> void

      def merge_sort: (untyped?, Hash[String, Field]) -> untyped

      def prepare_filters: (Hash[untyped, untyped]) -> Hash[Field, Hash[Symbol, untyped]]

      def setup_pagination: (untyped, untyped, total_count: Integer) -> void
    end
  end
end
