module TinyAdmin
  module Views
    module Components
      class FiltersForm
        attr_accessor filters: (Hash[Field, Hash[Symbol, untyped]])
        attr_accessor section_path: String

        def template: () ?{ (untyped) -> void } -> void
      end
    end
  end
end
