module TinyAdmin
  module Views
    module Components
      class Flash
        attr_accessor messages: Hash[Symbol, Array[String]?]?

        def view_template: () ?{ (untyped) -> void } -> void
      end
    end
  end
end
