module TinyAdmin
  module Views
    module Components
      class Widgets
        @widgets: Array[untyped]?

        def initialize: (Array[untyped]?) -> void

        def view_template: () ?{ (untyped) -> void } -> void
      end
    end
  end
end
