module TinyAdmin
  module Views
    module Components
      class Widgets
        @widgets: Array[untyped]?
        @context: Hash[Symbol, untyped]

        def initialize: (Array[untyped]?, ?context: Hash[Symbol, untyped]) -> void

        def view_template: () ?{ (untyped) -> void } -> void

        private

        def build_widget: (Class) -> untyped
      end
    end
  end
end
