module TinyAdmin
  module Views
    class BasicLayout
      include Attributes
      include Utils

      attr_accessor content: untyped
      attr_accessor params: untyped
      attr_accessor widgets: untyped

      def label_for: (String, options: Array[untyped]) -> String?
    end
  end
end
