module TinyAdmin
  module Views
    module Actions
      class Show
        attr_accessor actions: Hash[String, untyped]
        attr_accessor fields: Hash[String, Field]
        attr_accessor prepare_record: Proc
        attr_accessor record: untyped
        attr_accessor reference: untyped
        attr_accessor slug: String

        def view_template: () ?{ (untyped) -> void } -> void

        private

        def actions_buttons: () -> void
      end
    end
  end
end
