module TinyAdmin
  module Views
    module Pages
      class ErrorPage < DefaultLayout
        def view_template: () -> void

        private

        def css_class: () -> String
      end
    end
  end
end
