module TinyAdmin
  module Views
    module Pages
      class RecordNotFound < DefaultLayout
        def view_template: () ?{ () -> void } -> void

        def title: () -> String
      end
    end
  end
end
