---
name: Specs Rails 7.0

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Create database
        run: cd spec/dummy && bundle exec rails db:create

      - name: Apply migrations
        run: cd spec/dummy && bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec --profile
